### ISSUE TITLE
mmec using weights (W)

### ISSUE THREAD

**Issue by GregorDall** [covaruber/sommer#42] opened 2022-08-26 06:59 UTC
Dear Eduardo,

I have tried implementing the new mmec function. For the most part it seems to work great, but I am having issues when using weights. In my application I am using 1/se^2  from a first stage analysis as weights in the "weights" argument of mmer. Switching to mmec I will have to use the weights matrix (W). Using "weights" or "W" delivers the same results in mmer as you can see in the example I have provided (1). mmer and mmec also produce the same output in my example, when I do not use weights (2). The problem arises when I include weights (W) in mmec, it produces very different results, for the variance estimates and random effects (3). Maybe I have misspecified the W matrix? I appreciate any advice. 

Best Gregor

`
data(DT_example)
DT <- DT_example
head(DT)

### (1) compare mmer results with different weights arguments
DT$wt <- 1/as.numeric(DT$Year )^2
myW <- diag(DT$wt)

ans1 <- mmer(Yield~Env,
						 random= ~ Name + Env:Name,
						 rcov= ~ units,
						 weights = wt,
						 verbose = FALSE,
						 data=DT)

ans2 <- mmer(Yield~Env,
						 random= ~ Name + Env:Name,
						 rcov= ~ units,
						 W = myW,
						 verbose = FALSE,
						 data=DT)

unlist(ans1$sigma)
unlist(ans2$sigma)

ans1$Beta
ans2$Beta

ans1$U$Name$Yield[1:5] 
ans2$U$Name$Yield[1:5]

### (2) compare mmer and mmec results without weights

ans1 <- mmer(Yield~Env,
						 random= ~ Name + Env:Name,
						 rcov= ~ units,
						 verbose = FALSE,
						 data=DT)

ans2 <- mmec(Yield~Env,
						 random= ~ Name + Env:Name,
						 rcov= ~ units,
						 verbose = FALSE,
						 data=DT)

unlist(ans1$sigma)
unlist(ans2$sigma)

ans1$Beta
ans2$b

ans1$U$Name$Yield[1:5]
ans2$u[1:5]

### (3) compare mmer and mmec results with! weights

DT$wt <- 1/as.numeric(DT$Year )^2
myW <- diag(DT$wt)

ans1 <- mmer(Yield~Env,
						 random= ~ Name + Env:Name,
						 rcov= ~ units,
						 W = myW,
						 verbose = FALSE,
						 data=DT)

ans2 <- mmec(Yield~Env,
						 random= ~ Name + Env:Name,
						 rcov= ~ units,
						 W = as(myW, Class="sparseMatrix"),
						 verbose = FALSE,
						 data=DT)

unlist(ans1$sigma)
unlist(ans2$sigma)

ans1$Beta
ans2$b

ans1$U$Name$Yield[1:5]
ans2$u[1:5]
`

**Comment by covaruber** [comment] 2022-09-02 04:40
Dear Gregor thanks for catching this bug. The issue is that the W matrix is not being used despite you're specifying it. That's because I naively put an if statement indicating that if there wasn't a complex residual structure specified the R matrix shouldn't be used, which at the same time is built with W. I will fix that and push it tomorrow.

In addition, the right way to specify the W is opposite to the weights argument:

DT$wt <- 1/as.numeric(DT$Year )^2
myW <- diag(DT$wt)

m1 <- mmer(..., weights = wt,...) or mmer(..., W=W, ...)
m2 <- mmec(..., W=W, ...)

Once again, thanks for the report.

Cheers,
Eduardo

**Comment by covaruber** [comment] 2022-09-02 13:32
It has been fixed in the GitHub version. I will push to cran in the next days. Thanks!

Eduardo

**Comment by GregorDall** [comment] 2022-09-02 13:48
Thanks for the quick response, 
Cheers Gregor

**Comment by covaruber** [comment] 2022-09-02 15:11
I just noticed that still the VC are not correct when using the weights. I need to check what is wrong. I'll leave it open for now. Thanks.

Eduardo

**Comment by covaruber** [comment] 2023-01-07 13:52
Has been finally fixed and pushed to GitHub, sorry for the delay. Took me a while to see where was the bug.

Cheers,
Eduardo

**Closed by covaruber** 2023-01-07 13:52 UTC
Labels: bug
